trigger:
  branches:
    include:
    - master


#pool: yourPoolHere - ubuntu20-04 was tested.


stages:
- stage: Verify  
  jobs:
  - job: CheckSomeStuff
    steps:
    - task: AzureCLI@2
      displayName: Check out the agent capabilities
      inputs:
        scriptType: bash
        azureSubscription: <your-sub-here>
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: |
          pulumi version
          node --version
          tsc --version
          
    - task: AzureCLI@2
      displayName: Running basic pulumi automation
      env: 
        PULUMI_CONFIG_PASSPHRASE: password
      inputs:
        scriptType: bash
        azureSubscription: <your-sub-here>
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        inlineScript: |                    
          npm i    
          PULUMI_DEBUG_PROMISE_LEAKS=true npm run start
          
          


